require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ticket_soportes", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # TicketSoporte. As you add validations to TicketSoporte, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # TicketSoportesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      TicketSoporte.create! valid_attributes
      get ticket_soportes_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ticket_soporte = TicketSoporte.create! valid_attributes
      get ticket_soporte_url(ticket_soporte), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TicketSoporte" do
        expect {
          post ticket_soportes_url,
               params: { ticket_soporte: valid_attributes }, headers: valid_headers, as: :json
        }.to change(TicketSoporte, :count).by(1)
      end

      it "renders a JSON response with the new ticket_soporte" do
        post ticket_soportes_url,
             params: { ticket_soporte: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TicketSoporte" do
        expect {
          post ticket_soportes_url,
               params: { ticket_soporte: invalid_attributes }, as: :json
        }.to change(TicketSoporte, :count).by(0)
      end

      it "renders a JSON response with errors for the new ticket_soporte" do
        post ticket_soportes_url,
             params: { ticket_soporte: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ticket_soporte" do
        ticket_soporte = TicketSoporte.create! valid_attributes
        patch ticket_soporte_url(ticket_soporte),
              params: { ticket_soporte: invalid_attributes }, headers: valid_headers, as: :json
        ticket_soporte.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the ticket_soporte" do
        ticket_soporte = TicketSoporte.create! valid_attributes
        patch ticket_soporte_url(ticket_soporte),
              params: { ticket_soporte: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq("application/json")
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the ticket_soporte" do
        ticket_soporte = TicketSoporte.create! valid_attributes
        patch ticket_soporte_url(ticket_soporte),
              params: { ticket_soporte: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ticket_soporte" do
      ticket_soporte = TicketSoporte.create! valid_attributes
      expect {
        delete ticket_soporte_url(ticket_soporte), headers: valid_headers, as: :json
      }.to change(TicketSoporte, :count).by(-1)
    end
  end
end
